from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import get_args, get_origin

from pydantic import BaseModel

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "services" / "core" / "src"))

from academic_agent_core.schemas import SCHEMA_MODELS  # noqa: E402

GENERATED = ROOT / "packages" / "schemas" / "src" / "generated"


def _ts_type(annotation: object) -> str:
    origin = get_origin(annotation)
    args = get_args(annotation)
    if origin is None:
        if annotation is type(None):
            return "null"
        if annotation is str:
            return "string"
        if annotation is int:
            return "number"
        if annotation is bool:
            return "boolean"
        if annotation is float:
            return "number"
        if annotation is dict:
            return "Record<string, unknown>"
        if annotation is list:
            return "unknown[]"
        if isinstance(annotation, type) and issubclass(annotation, BaseModel):
            return annotation.__name__
        return "unknown"
    if origin is list:
        return f"{_ts_type(args[0])}[]"
    if origin is dict:
        return "Record<string, unknown>"
    if origin is type(None):
        return "null"
    if origin.__name__ == "Literal":
        return " | ".join(json.dumps(arg) for arg in args)
    if origin in (tuple,):
        return "unknown[]"
    if origin in (type(str | None),):
        return " | ".join(_ts_type(arg) for arg in args)
    if str(origin) == "typing.Union":
        return " | ".join(_ts_type(arg) for arg in args)
    return "unknown"


def _is_optional(annotation: object) -> bool:
    return type(None) in get_args(annotation)


def generate_types(models: tuple[type[BaseModel], ...]) -> str:
    chunks = [
        "/* Auto-generated by scripts/export_schema.py. Do not edit by hand. */",
        "export type JsonObject = Record<string, unknown>;",
        "",
    ]
    for model in models:
        chunks.append(f"export interface {model.__name__} {{")
        for name, field in model.model_fields.items():
            optional = "?" if not field.is_required() else ""
            chunks.append(f"  {name}{optional}: {_ts_type(field.annotation)};")
        chunks.append("}")
        chunks.append("")
    return "\n".join(chunks)


def main() -> None:
    GENERATED.mkdir(parents=True, exist_ok=True)
    schema_bundle = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "Academic Agent v0 Schemas",
        "models": {model.__name__: model.model_json_schema() for model in SCHEMA_MODELS},
    }
    (GENERATED / "schema.json").write_text(
        json.dumps(schema_bundle, ensure_ascii=False, indent=2, sort_keys=True),
        encoding="utf-8",
    )
    (GENERATED / "types.ts").write_text(
        generate_types(SCHEMA_MODELS),
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
